# Generated by Django 5.0.2 on 2024-02-14 09:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_cessation', models.DateField(default=datetime.datetime(9999, 12, 31, 0, 0))),
                ('modifier_par', models.CharField(max_length=10)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_cessation', models.DateField(default=datetime.datetime(9999, 12, 31, 0, 0))),
                ('modifier_par', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=10)),
                ('adresse', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profil_utilisateur', to='project.profil')),
            ],
        ),
    ]
