# Generated by Django 5.0.2 on 2024-02-28 07:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddUsersFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_xl', models.FileField(null=True, upload_to='excel_files')),
            ],
        ),
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_cessation', models.DateField(default=datetime.datetime(9999, 12, 31, 0, 0))),
                ('modifier_par', models.CharField(max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('intitule', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('geolocalisation_longitude', models.FloatField(default=0)),
                ('geolocalisation_latitude', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_cessation', models.DateField(default=datetime.datetime(9999, 12, 31, 0, 0))),
                ('modifier_par', models.CharField(max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('telephone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_cessation', models.DateField(default=datetime.datetime(9999, 12, 31, 0, 0))),
                ('modifier_par', models.CharField(max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('denomination', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OptionSupplementaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_cessation', models.DateField(default=datetime.datetime(9999, 12, 31, 0, 0))),
                ('modifier_par', models.CharField(max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('libelle', models.CharField(max_length=100)),
                ('montant', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_cessation', models.DateField(default=datetime.datetime(9999, 12, 31, 0, 0))),
                ('modifier_par', models.CharField(max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_cessation', models.DateField(default=datetime.datetime(9999, 12, 31, 0, 0))),
                ('modifier_par', models.CharField(max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('intitule', models.CharField(max_length=100)),
                ('montant', models.FloatField(default=0)),
                ('couleur', models.CharField(default='#fff', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatutDemande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_cessation', models.DateField(default=datetime.datetime(9999, 12, 31, 0, 0))),
                ('modifier_par', models.CharField(max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_cessation', models.DateField(default=datetime.datetime(9999, 12, 31, 0, 0))),
                ('modifier_par', models.CharField(max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('intitule', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_cessation', models.DateField(default=datetime.datetime(9999, 12, 31, 0, 0))),
                ('modifier_par', models.CharField(max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('observations', models.TextField(default='RAS')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_demande', to='project.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_demande', to='project.service')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statut_demande', to='project.statutdemande')),
            ],
        ),
        migrations.CreateModel(
            name='OptionSupplementaireDemande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_cessation', models.DateField(default=datetime.datetime(9999, 12, 31, 0, 0))),
                ('modifier_par', models.CharField(max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nombre', models.IntegerField(default=0)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_option_supplementaire', to='project.demande')),
                ('option_supplementaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_supplementaire_demande', to='project.optionsupplementaire')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_cessation', models.DateField(default=datetime.datetime(9999, 12, 31, 0, 0))),
                ('modifier_par', models.CharField(max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('denomination', models.CharField(max_length=100)),
                ('entite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entite_structure', to='project.entite')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_service', to='project.structure'),
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_cessation', models.DateField(default=datetime.datetime(9999, 12, 31, 0, 0))),
                ('modifier_par', models.CharField(max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=10)),
                ('adresse', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='photos/profil')),
                ('is_active', models.BooleanField(default=False)),
                ('can_connect', models.BooleanField(default=True)),
                ('agence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agence_utilisateur', to='project.agence')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profil_utilisateur', to='project.profil')),
            ],
        ),
        migrations.AddField(
            model_name='demande',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_demande', to='project.utilisateur'),
        ),
    ]
