# Generated by Django 5.0.2 on 2024-02-21 08:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionSupplementaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_cessation', models.DateField(default=datetime.datetime(9999, 12, 31, 0, 0))),
                ('modifier_par', models.CharField(max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('libelle', models.CharField(max_length=100)),
                ('montant', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OptionSupplementaireDemande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_cessation', models.DateField(default=datetime.datetime(9999, 12, 31, 0, 0))),
                ('modifier_par', models.CharField(max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_option_supplementaire', to='project.demande')),
                ('option_supplementaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_supplementaire_demande', to='project.optionsupplementaire')),
            ],
        ),
    ]
