# Generated by Django 5.0.2 on 2024-03-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_agence_geolocalisation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='modifier_par',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='modifier_par',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='demande',
            name='modifier_par',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='entite',
            name='modifier_par',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='optionsupplementaire',
            name='modifier_par',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='optionsupplementairedemande',
            name='modifier_par',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='profil',
            name='modifier_par',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='modifier_par',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='statutdemande',
            name='modifier_par',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='structure',
            name='modifier_par',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='modifier_par',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='ville',
            name='modifier_par',
            field=models.CharField(default='', max_length=10),
        ),
    ]
