# Generated by Django 5.0.2 on 2024-02-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_optionsupplementaire_optionsupplementairedemande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionsupplementaire',
            name='montant',
            field=models.IntegerField(default=0),
        ),
    ]
