# Generated by Django 5.0.2 on 2024-03-06 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_agence_modifier_par_client_modifier_par_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='date_cessation',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0)),
        ),
        migrations.AlterField(
            model_name='agence',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_cessation',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0)),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='date_cessation',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0)),
        ),
        migrations.AlterField(
            model_name='demande',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='entite',
            name='date_cessation',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0)),
        ),
        migrations.AlterField(
            model_name='entite',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='optionsupplementaire',
            name='date_cessation',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0)),
        ),
        migrations.AlterField(
            model_name='optionsupplementaire',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='optionsupplementairedemande',
            name='date_cessation',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0)),
        ),
        migrations.AlterField(
            model_name='optionsupplementairedemande',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='date_cessation',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0)),
        ),
        migrations.AlterField(
            model_name='profil',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_cessation',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0)),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='statutdemande',
            name='date_cessation',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0)),
        ),
        migrations.AlterField(
            model_name='statutdemande',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='date_cessation',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0)),
        ),
        migrations.AlterField(
            model_name='structure',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_cessation',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0)),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='date_cessation',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0)),
        ),
        migrations.AlterField(
            model_name='ville',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
