# Generated by Django 5.0.2 on 2024-02-14 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_profil_is_deleted_utilisateur_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
