# Generated by Django 5.0.2 on 2024-02-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.FileField(default='', upload_to='photos/profil'),
        ),
    ]
