# Generated by Django 5.0.2 on 2024-02-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_optionsupplementaire_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='observation',
            field=models.TextField(default=''),
        ),
    ]
