# Generated by Django 5.0.2 on 2024-02-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_demande_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='frais_supplementaire',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='nb_impression',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='nb_scannage',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='raisons_frais_sup',
        ),
    ]
