# Generated by Django 5.0.2 on 2024-02-14 23:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_utilisateur_date_naissance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddUsersFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_xl', models.FileField(null=True, upload_to='excel_files')),
            ],
        ),
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_cessation', models.DateField(default=datetime.datetime(9999, 12, 31, 0, 0))),
                ('modifier_par', models.CharField(max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('intitule', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('geolocalisation_longitude', models.IntegerField(default=0)),
                ('geolocalisation_latitude', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_cessation', models.DateField(default=datetime.datetime(9999, 12, 31, 0, 0))),
                ('modifier_par', models.CharField(max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('telephone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_cessation', models.DateField(default=datetime.datetime(9999, 12, 31, 0, 0))),
                ('modifier_par', models.CharField(max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='agence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agence_utilisateur', to='project.agence'),
        ),
    ]
