# Generated by Django 5.0.2 on 2024-03-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_agence_date_cessation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('validate', models.BooleanField(default=False)),
            ],
        ),
    ]
