# Generated by Django 5.0.2 on 2024-02-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_demande_frais_supplementaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionsupplementairedemande',
            name='nombre',
            field=models.IntegerField(default=0),
        ),
    ]
