# Generated by Django 5.0.2 on 2024-02-16 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_utilisateur_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='entite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entite_structure', to='project.entite'),
        ),
    ]
