# Generated by Django 5.0.2 on 2024-03-15 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_validation_agence_validation_validator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationDemande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('demande', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.demande')),
                ('validation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='project.validation')),
            ],
        ),
    ]
