# Generated by Django 5.0.2 on 2024-02-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_structure_entite'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='picture',
            field=models.ImageField(blank=True, upload_to='photos/service'),
        ),
    ]
