# Generated by Django 5.0.2 on 2024-02-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_optionsupplementairedemande_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='observation',
            new_name='observations',
        ),
    ]
