# Generated by Django 5.0.2 on 2024-02-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_service_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='denomination',
            new_name='intitule',
        ),
    ]
