# Generated by Django 5.0.2 on 2024-02-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_observation_demande_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='observations',
            field=models.TextField(default='RAS'),
        ),
    ]
