# Generated by Django 5.0.2 on 2024-03-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_validationdemande'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='montant',
            field=models.IntegerField(null=True),
        ),
    ]
