# Generated by Django 5.0.2 on 2024-02-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_rename_denomination_service_intitule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='picture',
            new_name='photo',
        ),
    ]
