# Generated by Django 5.0.2 on 2024-02-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_rename_picture_service_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='agent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='agent_demande', to='project.utilisateur'),
            preserve_default=False,
        ),
    ]
