# Generated by Django 5.0.2 on 2024-03-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_service_delai'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
