# Generated by Django 5.0.2 on 2024-02-19 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_demande_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='service_demande', to='project.service'),
            preserve_default=False,
        ),
    ]
