# Generated by Django 5.0.2 on 2024-02-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_demande_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='frais_supplementaire',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='montant',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='nb_impression',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='nb_scannage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='raisons_frais_sup',
            field=models.CharField(default='', max_length=100),
        ),
    ]
